# Docs for the Azure Web Apps Deploy action: https://github.com/azure/functions-action
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Powershell project to Azure Function App - cippaoif7

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: '.'

jobs:
  deploy:
    runs-on: windows-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout GitHub Action
        uses: actions/checkout@v4

      - name: Create version.json
        shell: pwsh
        run: |
          $Version = (Get-Content version_latest.txt).Trim()
          $Commit = "${env:GITHUB_SHA}".Substring(0,7)
          @{
              version = $Version
              commit  = $Commit
          } | ConvertTo-Json -Compress | Out-File version.json

      - name: Build CIPP Modules
        shell: pwsh
        run: |
          ./Tools/Build-DevApiModules.ps1

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_19588DF9A9704B35AE53FC4465C5FDFB }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_D871CD05C34244D0979E2AB00FBFE4F1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_74172E0205BF48DEBA10DF30A1A1E42C }}

      - name: Run Azure Functions Action
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'cippaoif7'
          slot-name: 'Production'
          package: ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}
